#!/bin/bash

echo "Ttools-"
echo

if [ $# -eq 0 ]

then
	for i in {1..3}
		do
		    echo
	done
	echo Ttools Scripts:
	echo _________________________ 
	for file in /home/snorkeboy/bin/ttools/*; do
	  echo ${file##*/}
	done
	echo _________________________

	   
	   
else

	#/home/snorkeboy/bin/ttools/test2 ${@:2}
	
	  
	  
	FILE="$1"
	if [ -e /home/snorkeboy/bin/ttools/"$FILE" ]
	then
	    /home/snorkeboy/bin/ttools/${@:1} ${@:2}
	else
	    echo "that file does not exist in /home/snorkeboy/bin/ttools/"
	fi
	  		


fi
